# Generated by Django 4.2.3 on 2023-07-22 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_appeal_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appeal',
            old_name='owner',
            new_name='user',
        ),
    ]
