# Generated by Django 4.2.3 on 2023-07-22 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_owner_appeal_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appeal',
            old_name='user',
            new_name='owner',
        ),
    ]
