version: '3.7'

networks:
  appeals-service:
    driver: bridge

services:
  appeals-postgresql:
    restart: always
    image: postgres:latest
    env_file:
      - .env
    environment:
      PGDATA: /var/lib/postgresql/auth_data
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      - appeals-service

  appeals-service:
    restart: always
    depends_on:
      - appeals-postgresql
    env_file:
      - .env
    build:
      context: ..
      dockerfile: docker/backend.dockerfile
    ports:
      - 8080:8080
    networks:
      - appeals-service

#  celery-worker:
#    build:
#      context: ..
#      dockerfile: docker/celery-worker.dockerfile
#    env_file:
#      - .env
#    depends_on:
#      - iam-service
#      - redis
#
#  celery-beat:
#    build:
#      context: ..
#      dockerfile: docker/celery-beat.dockerfile
#    env_file:
#      - .env
#    depends_on:
#      - iam-service
#      - redis
#    networks:
#      - iam-service
#
#  redis:
#    image: redis:7
#    networks:
#      - iam-service
#
#  dashboard:
#    build:
#      context: ..
#      dockerfile: docker/backend.dockerfile
#    command: celery --broker=redis://redis:6379/0 flower --port=5555
#    ports:
#      - 5556:5555
#    env_file:
#      - .env
#    depends_on:
#      - iam-service
#      - redis
#      - celery-worker
#      - celery-beat
#    networks:
#      - iam-service
